In [122]:
NAME = "Bohan YANG"
StudentID = "2330016056"

---

# Pandas

In the previous lectures, we dove into detail on NumPy and its ``ndarray`` object, which provides efficient storage and manipulation of dense typed arrays in Python. In this section, we will look in detail at the data structures provided by the **Pandas** library.

<img src = "img/Pandas_logo.png" size = "400">

- Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a ``DataFrame``.

- ``DataFrame``'s are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.

- As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

As we saw, NumPy's ``ndarray`` data structure provides essential features for the type of **clean, well-organized data** typically seen in **numerical computing** tasks.
While it serves this purpose very well, its limitations become clear when we need more flexibility (e.g., attaching labels to data, working with missing data, etc.), which is an important piece of analyzing the less structured data available in many forms in the world around us.

# Installing and Using Pandas

Installation of Pandas on your system requires NumPy to be installed, and if building the library from source, requires the appropriate tools to compile the C and Cython sources on which Pandas is built.
Details on this installation can be found in the [Pandas documentation](http://pandas.pydata.org/).
If you installed Anaconda, you already have Pandas installed.

* Pandas = **Panel, DataFrame and Series**. (Note there is a s at the end of Pandas.)
<img src="img\Pandas-vs-NumPy.jpg" width="500px">
Once Pandas is installed, you can import it and check the version:

In [123]:
import pandas
pandas.__version__

'2.2.1'

Just as we generally import NumPy under the alias ``np``, we will import Pandas under the alias ``pd``:

In [124]:
import pandas as pd

This import convention will be used throughout the remainder of our notes.

# 1 Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which **the rows and columns are identified with labels rather than simple integer indices**.
- Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
- Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the **``Series``**, **``DataFrame``**, and **``Index``**.

We will start our code sessions with the standard NumPy and Pandas imports:

In [125]:
import numpy as np
import pandas as pd

## 1.1 The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [126]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [127]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [128]:
data.index

RangeIndex(start=0, stop=4, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [129]:
data[1]

0.5

In [130]:
data[1:3]

1    0.50
2    0.75
dtype: float64

The Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy array that it emulates.

### ``Series`` as generalized NumPy array

- From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.

- The essential difference is the **presence of the index**: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an *explicitly defined* index associated with the values.

- This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.


For example, if we wish, we can use **strings as an index**:

In [131]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

And the item access works as expected:

In [132]:
data['a']

0.25

In [133]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

The dtype object comes from NumPy, it describes the type of element in a ndarray. Every element in a ndarray must has the same size in byte. For int64 and float64, they are 8 bytes. But for strings, the length of the string is not fixed. So instead of save the bytes of strings in the ndarray directly, Pandas use object ndarray, <mark>which save pointers to objects</mark>, because of this the dtype of this kind ndarray is object.

We can even use non-contiguous or non-sequential indices:

In [134]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [135]:
data[5]

0.5

In [136]:
data.index

Index([2, 5, 3, 7], dtype='int64')

### Series as specialized dictionary

- In this way, you can think of a Pandas ``Series`` a bit like a specialization of a **Python dictionary**.
- A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps **typed keys to a set of typed values**.
- This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [137]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

By default, a ``Series`` will be created where the index is drawn from the sorted keys.
From here, typical dictionary-style item access can be performed:

In [138]:
population['California']

38332521

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [139]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [140]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [141]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [142]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

``data`` can be a dictionary, in which ``index`` defaults to the dictionary keys:

In [143]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

The index can be explicitly set if a different result is preferred:

In [144]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

Notice that in this case, the ``Series`` is **populated only with the explicitly identified keys**.

**Q1**: What is the difference between a series and a one dimensional array?

**Q2**: What is the difference between a series and a dictionary?

## 1.2 The Pandas DataFrame Object

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be thought of either as a **generalization of a NumPy array**, or as a **specialization of a Python dictionary**.
We'll now take a look at each of these perspectives.

### DataFrame as a generalized NumPy array
- If a ``Series`` is an analog of a one-dimensional array with flexible indices, a ``DataFrame`` is <mark>an analog of a two-dimensional array with both flexible row indices and flexible column names</mark>.

- Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects. **Here, by "aligned" we mean that they share the same index.**

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

In [145]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [146]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [147]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [148]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [149]:
states.columns

Index(['population', 'area'], dtype='object')

Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

### DataFrame as specialized dictionary

Similarly, we can also think of a ``DataFrame`` as a specialization of a dictionary.
- A dictionary maps a key to a value
- A ``DataFrame`` maps a **column name** to **a ``Series`` of column data**.


For example, asking for the ``'area'`` attribute returns the ``Series`` object containing the areas we saw earlier:

In [150]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

You can get the specific column as a Series by following code:

In [151]:
states[states.columns[0]] #states.columns[0] is area

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### Constructing DataFrame objects

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### From a single Series object

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

In [152]:
pd.DataFrame(population)

                   0
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

In [153]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

Any list of dictionaries can be made into a ``DataFrame``.
We'll use a simple list comprehension to create some data:

In [154]:
data = [{'a': i, 'b': 2 * i} for i in range (3)]
print(data)
pd.DataFrame(data)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

   a  b
0  0  0
1  1  2
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with ``NaN`` (i.e., "not a number") values:

In [155]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

As we saw before, a ``DataFrame`` can be constructed from **a dictionary of ``Series`` objects** as well:

In [156]:
pd.DataFrame({'population': population,
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
If omitted, an integer index will be used for each:

In [157]:
import numpy as np
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.959075  0.773358
b  0.167377  0.599367
c  0.094078  0.638090

In [158]:
pd.DataFrame(np.random.rand(4))

          0
0  0.054886
1  0.208044
2  0.914722
3  0.374317

**Q3**: What is the difference between a data frame and a two dimensional array?

## 1.3 The Pandas Index Object

- We have seen here that both the ``Series`` and ``DataFrame`` objects contain an explicit *index* that lets you reference and modify data.
- This ``Index`` object is an interesting structure in itself, and it can be thought of either as an *immutable array* or as an *ordered set* (technically a multi-set, as ``Index`` objects may contain repeated values).

As a simple example, let's construct an ``Index`` from a list of integers:

In [159]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

The ``Index`` in many ways operates like an array.
For example, we can use standard Python indexing notation to retrieve values or slices:

In [160]:
ind[1]

3

In [161]:
ind[::2]

Index([2, 5, 11], dtype='int64')

``Index`` objects also have many of the attributes familiar from NumPy arrays:

In [162]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

One difference between ``Index`` objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [163]:
ind[1] = 0

TypeError: Index does not support mutable operations

This immutability makes it safer to share indices between multiple ``DataFrame``s and arrays, without the potential for side effects from inadvertent index modification.

### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic.
The ``Index`` object follows many of the conventions used by Python's built-in ``set`` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:

In [164]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [165]:
indA & indB  # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [166]:
indA | indB  # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [167]:
indA ^ indB  # symmetric difference

Index([3, 0, 0, 0, 2], dtype='int64')

These operations may also be accessed via object methods, for example ``indA.intersection(indB)``.

# 2 Data Indexing and Selection <a class="tocSkip">

In the previous topic, we looked in detail at methods and tools to access, set, and modify values in NumPy arrays.
These included 
- Indexing (e.g., ``arr[2, 1]``)
- Slicing (e.g., ``arr[:, 1:5]``)
- Masking (e.g., ``arr[arr > 0]``) 
- Fancy indexing (e.g., ``arr[0, [1, 5]]``) 
and combinations thereof (e.g., ``arr[:, [1, 5]]``).

Here we'll look at similar means of accessing and modifying values in Pandas ``Series`` and ``DataFrame`` objects.

We'll start with the simple case of the one-dimensional ``Series`` object, and then move on to the more complicated two-dimesnional ``DataFrame`` object.

## 2.1 Data Selection in Series

As we saw in the previous section, a ``Series`` object acts in many ways like a one-dimensional NumPy array, and in many ways like a standard Python dictionary.
If we keep these two overlapping analogies in mind, it will help us to understand the patterns of data indexing and selection in these arrays.

### Series as dictionary

Like a dictionary, the ``Series`` object provides a mapping from a collection of keys to a collection of values:

In [168]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [169]:
data['b']

0.5

We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [170]:
'a' in data

True

In [171]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [172]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

``Series`` objects can even be modified with a dictionary-like syntax.
Just as you can extend a dictionary by assigning to a new key, you can extend a ``Series`` by assigning to a new index value:

In [173]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

This easy mutability of the objects is a convenient feature: under the hood, Pandas is making decisions about memory layout and data copying that might need to take place; the user generally does not need to worry about these issues.

### Series as one-dimensional array

A ``Series`` builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays – that is, *slices*, *masking*, and *fancy indexing*.
Examples of these are as follows:

In [174]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [175]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [176]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [177]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Notice that when slicing with an explicit index (i.e., ``data['a':'c']``), <mark>the final index is *included* in the slice</mark>, while when slicing with an implicit index (i.e., ``data[0:2]``), <mark>the final index is *excluded* from the slice</mark>.

### Indexers: loc and iloc

These slicing and indexing conventions can be a source of confusion.
For example, if your ``Series`` has an explicit integer index, **an indexing operation such as ``data[1]`` will use the explicit indices, while a slicing operation like ``data[1:3]`` will use the implicit Python-style index.**

In [178]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [179]:
# explicit index when indexing
data[1]

'a'

In [180]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special *indexer* attributes that explicitly expose certain indexing schemes.
These are not functional methods, but attributes that expose a particular slicing interface to the data in the ``Series``.

First, the ``loc`` attribute allows indexing and slicing that always references the explicit index:

In [181]:
data.loc[1]

'a'

In [182]:
data.loc[1:3]

1    a
3    b
dtype: object

The ``iloc`` attribute allows indexing and slicing that always references the implicit Python-style index:

In [183]:
data.iloc[1]

'b'

In [184]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that "explicit is better than implicit."
The explicit nature of ``loc`` and ``iloc`` make them very useful in maintaining clean and readable code; especially in the case of integer indexes, it is recommended using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

## 2.2 Data Selection in DataFrame

Recall that a ``DataFrame`` acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of ``Series`` structures sharing the same index.
These analogies can be helpful to keep in mind as we explore data selection within this structure.

### DataFrame as a dictionary

The first analogy we will consider is the ``DataFrame`` as a dictionary of related ``Series`` objects.
Let's return to our example of areas and populations of states:

In [185]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

The individual ``Series`` that make up the columns of the ``DataFrame`` can be accessed via dictionary-style indexing of the column name:

In [186]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Equivalently, we can use attribute-style access with column names that are strings:

In [187]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

This attribute-style column access actually accesses the exact same object as the dictionary-style access:

In [188]:
data.area is data['area']

True

In [189]:
data.area = 10000
data

             area       pop
California  10000  38332521
Texas       10000  26448193
New York    10000  19651127
Florida     10000  19552860
Illinois    10000  12882135

Though this is a useful shorthand, keep in mind that it does not work for all cases!
For example, if the column names are not strings, or if the column names conflict with methods of the ``DataFrame``, this attribute-style access is not possible.
For example, the ``DataFrame`` has a ``pop()`` method, so ``data.pop`` will point to this rather than the ``"pop"`` column:

In [190]:
data.pop is data['pop']

False

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use ``data['pop'] = 1000`` rather than ``data.pop = 1000``).

Like with the ``Series`` objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [191]:
data['density'] = data['pop'] / data['area']
data

             area       pop    density
California  10000  38332521  3833.2521
Texas       10000  26448193  2644.8193
New York    10000  19651127  1965.1127
Florida     10000  19552860  1955.2860
Illinois    10000  12882135  1288.2135

### DataFrame as two-dimensional array

As mentioned previously, we can also view the ``DataFrame`` as an enhanced two-dimensional array.
We can examine the raw underlying data array using the ``values`` attribute:

In [192]:
data.values

array([[1.0000000e+04, 3.8332521e+07, 3.8332521e+03],
       [1.0000000e+04, 2.6448193e+07, 2.6448193e+03],
       [1.0000000e+04, 1.9651127e+07, 1.9651127e+03],
       [1.0000000e+04, 1.9552860e+07, 1.9552860e+03],
       [1.0000000e+04, 1.2882135e+07, 1.2882135e+03]])

With this picture in mind, many familiar array-like observations can be done on the ``DataFrame`` itself.
For example, we can transpose the full ``DataFrame`` to swap rows and columns:

In [193]:
data

             area       pop    density
California  10000  38332521  3833.2521
Texas       10000  26448193  2644.8193
New York    10000  19651127  1965.1127
Florida     10000  19552860  1955.2860
Illinois    10000  12882135  1288.2135

In [194]:
data.T

           California         Texas      New York       Florida      Illinois
area     1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  3.833252e+03  2.644819e+03  1.965113e+03  1.955286e+03  1.288214e+03

When it comes to indexing of ``DataFrame`` objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array.
In particular, passing a single index to an array accesses a row:

In [195]:
data.values[0]

array([1.0000000e+04, 3.8332521e+07, 3.8332521e+03])

and **passing a single "index" to a ``DataFrame`` accesses a column**:

In [196]:
data['area']

California    10000
Texas         10000
New York      10000
Florida       10000
Illinois      10000
Name: area, dtype: int64

Thus for array-style indexing, we need another convention.
Here Pandas again uses the ``loc`` and ``iloc`` indexers mentioned earlier.

Using the ``iloc`` indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the ``DataFrame`` index and column labels are maintained in the result:

In [197]:
data.iloc[:3, :2]

             area       pop
California  10000  38332521
Texas       10000  26448193
New York    10000  19651127

Similarly, using the ``loc`` indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [198]:
data.loc[:'Illinois', :'pop']

             area       pop
California  10000  38332521
Texas       10000  26448193
New York    10000  19651127
Florida     10000  19552860
Illinois    10000  12882135

Any of the familiar NumPy-style data access patterns can be used within these indexers.
For example, in the ``loc`` indexer we can combine masking and fancy indexing as in the following:

In [199]:
data.loc[data.density > 100, ['pop', 'density']]

                 pop    density
California  38332521  3833.2521
Texas       26448193  2644.8193
New York    19651127  1965.1127
Florida     19552860  1955.2860
Illinois    12882135  1288.2135

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [200]:
data.iloc[0, 2] = 90
data

             area       pop    density
California  10000  38332521    90.0000
Texas       10000  26448193  2644.8193
New York    10000  19651127  1965.1127
Florida     10000  19552860  1955.2860
Illinois    10000  12882135  1288.2135

### Additional indexing conventions

There are a couple extra indexing conventions that might seem at odds with the preceding discussion, but nevertheless can be very useful in practice.
- First, **while *indexing* refers to columns, *slicing* refers to rows**:

In [201]:
data['Florida':'Illinois']

           area       pop    density
Florida   10000  19552860  1955.2860
Illinois  10000  12882135  1288.2135

Such slices can also refer to rows by number rather than by index:

In [202]:
data[1:3]

           area       pop    density
Texas     10000  26448193  2644.8193
New York  10000  19651127  1965.1127

- Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [203]:
data[data.density > 100]

           area       pop    density
Texas     10000  26448193  2644.8193
New York  10000  19651127  1965.1127
Florida   10000  19552860  1955.2860
Illinois  10000  12882135  1288.2135

These two conventions are syntactically similar to those on a NumPy array, and while these may not precisely fit the mold of the Pandas conventions, they are nevertheless quite useful in practice.

# 3 Operating on Data in Pandas <a class="tocSkip">

- One of the essential pieces of NumPy is the ability to perform quick element-wise operations,e.g.,
    - with basic arithmetic (addition, subtraction, multiplication, etc.)
    - with more sophisticated operations (trigonometric functions, exponential and logarithmic functions, etc.).
- Pandas inherits much of this functionality from NumPy, and the ufuncs that we introduced in numpy computation section are key to this.

- Pandas includes a couple useful twists: 
    - for unary operations like negation and trigonometric functions, these ufuncs will *preserve index and column labels* in the output
    - for binary operations such as addition and multiplication, Pandas will automatically *align indices* when passing the objects to the ufunc.


This means that keeping the context of data and combining data from different sources–both potentially error-prone tasks with raw NumPy arrays–become essentially foolproof ones with Pandas.
We will additionally see that there are well-defined operations between one-dimensional ``Series`` structures and two-dimensional ``DataFrame`` structures.

## 3.1 Ufuncs: Index Preservation

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas ``Series`` and ``DataFrame`` objects.
Let's start by defining a simple ``Series`` and ``DataFrame`` on which to demonstrate this:

In [204]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [205]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

If we apply a NumPy ufunc on either of these objects, the result will be another Pandas object *with the indices preserved:*

In [206]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

Or, for a slightly more complex calculation:

In [207]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

Any of the ufuncs discussed in the Computation on NumPy Arrays section can be used in a similar manner.

## 3.2 UFuncs: Index Alignment

For binary operations on two ``Series`` or ``DataFrame`` objects, Pandas will align indices in the process of performing the operation.
This is very convenient when working with incomplete data, as we'll see in some of the examples that follow.

### Index alignment in Series

As an example, suppose we are combining two different data sources, and find only the top three US states by *area* and the top three US states by *population*:

In [208]:
# The name argument allows you to give a name to a Series object, i.e. to the column.
# So that when you'll put that in a DataFrame, the column will be named according to the name parameter.

area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

Let's see what happens when we divide these to compute the population density:

In [209]:
dfarea = pd.DataFrame(area)
dfpopulation = pd.DataFrame(population)
dfarea

               area
Alaska      1723337
Texas        695662
California   423967

In [210]:
dfpopulation

            population
California    38332521
Texas         26448193
New York      19651127

In [211]:
df_result = pd.DataFrame(population / area)
df_result

                    0
Alaska            NaN
California  90.413926
New York          NaN
Texas       38.018740

The resulting array contains the *union* of indices of the two input arrays.

Any item for which one or the other does not have an entry is marked with ``NaN``, or "Not a Number," which is how Pandas marks missing data.
This index matching is implemented this way for any of Python's built-in arithmetic expressions; any missing values are filled in with NaN by default:

In [212]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, the fill value can be modified using appropriate object methods in place of the operators.
For example, calling ``A.add(B)`` is equivalent to calling ``A + B``, but allows optional explicit specification of the fill value for any elements in ``A`` or ``B`` that might be missing:

In [213]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

A similar type of alignment takes place for *both* columns and indices when performing operations on ``DataFrame``s:

In [214]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

   A   B
0  1  11
1  5   1

In [215]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [216]:
A + B

      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

Notice that **indices are aligned correctly irrespective of their order in the two objects**, and indices in the result are sorted.
As was the case with ``Series``, we can use the associated object's arithmetic method and pass any desired ``fill_value`` to be used in place of missing entries.
Here we'll fill with the mean of all values in ``A`` (computed by first stacking the rows of ``A``):

In [217]:
# stack method reshaped DataFrame or Series having a multi-level index with one or more new inner-most levels  
# http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html
fill = A.stack().mean()
print (fill)
print (A)
A.add(B, fill_value=fill)

4.5
   A   B
0  1  11
1  5   1

      A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

The following table lists Python operators and their equivalent Pandas object methods:

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |

## 3.3  Ufuncs: Operations Between DataFrame and Series

When performing operations between a ``DataFrame`` and a ``Series``, the index and column alignment is similarly maintained.
Operations between a ``DataFrame`` and a ``Series`` are similar to operations between a two-dimensional and one-dimensional NumPy array.
Consider one common operation, where we find the difference of a two-dimensional array and one of its rows:

In [218]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [219]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

According to NumPy's broadcasting rules, subtraction between a two-dimensional array and one of its rows is applied row-wise.

In Pandas, the convention similarly operates row-wise by default:

In [220]:
df = pd.DataFrame(A, columns=list('QRST'))
df

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [221]:
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

If you would instead like to operate column-wise, you can use the object methods mentioned earlier, while specifying the ``axis`` keyword:

In [222]:
# Axis to target. Can be either the axis name (‘index’) or number (0)
df.subtract(df['R'], axis=0)

   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [223]:
df.subtract(df['R'],axis='index')

   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

Note that these ``DataFrame``/``Series`` operations, like the operations discussed above, will automatically align  indices between the two elements:

In [224]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [225]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

This preservation and alignment of indices and columns means that operations on data in Pandas will always maintain the data context, which prevents the types of silly errors that might come up when working with heterogeneous and/or misaligned data in raw NumPy arrays.

## 4 Import and inspect data 
- In this case, we will analyze a ready-made dataset by Gapminder https://www.gapminder.org/
- More data can be found here: https://www.gapminder.org/data/

In [226]:
# a common way to import the "ready-made" or harvested data, normally in csv format 
# the data file used in this tutorial is from this tutorial: "https://storage.googleapis.com/learn_pd_like_tidyverse/gapminder.csv"
# special thanks for the original author for compiling and sharing this dataset 

gapminder = pd.read_csv('./Data/gapminder_cleaned_2.csv')

- Using Excel, open this csv file and check its contents.
- Be careful that you don't make changes to this csv file in Excel.
- A safe way is to make a copy of the csv file, and then open the copy with Excel.

Note: reading and writing (external) data with Pandas (Nelli, 2018, p. 142) 

<img src = "img/pd_IO.png" width =300>

In [227]:
# checkin the type and take a glance at the head 
print(type(gapminder))
gapminder.head(3)    # show the first 3 rows of data

<class 'pandas.core.frame.DataFrame'>

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [228]:
gapminder.tail(3)   # Show the last 3 rows of data

       country continent  year  lifeExp       pop   gdpPercap
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

### 4A. Examining the attributes of the Data Frame (standard procedures)

- ```df.info()```
- ```df.shape``` (similar to "dim" in R) 
- ```df.columns``` (check the variables, similar to "names" in R) 
- ```df.index``` (check the index of the "rows") 
- ```df.describe()``` (descriptive statistics for numerical variables) 
- Note that methods (functions) have parentheses, and attributes (values) don't.

In [229]:
gapminder.info()

# Shows info of the columns (name and data type) and
# number of rows (compare with results from the tail() command)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [230]:
gapminder.shape 
# (the number of cases/observations/rows, the number of variables/columns)

(1704, 6)

In [231]:
gapminder.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [232]:
gapminder.index

RangeIndex(start=0, stop=1704, step=1)

In [233]:
gapminder.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900